# Generated by Django 4.2.29 on 2026-04-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_seekerprofile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seekerprofile",
            name="resume",
        ),
    ]
